// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw-0IWqhiN-qf3u1ZlRk-ypwjhwIpzbAY',
    appId: '1:8731740027:web:506e53a2a6153d852e9fde',
    messagingSenderId: '8731740027',
    projectId: 'basededatos-c4252',
    authDomain: 'basededatos-c4252.firebaseapp.com',
    storageBucket: 'basededatos-c4252.firebasestorage.app',
    measurementId: 'G-6NW1CX1G74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5PkaMkhGyMy2Aqm-prUGKZh2VE4ilSxs',
    appId: '1:8731740027:android:272ce035e58b1c892e9fde',
    messagingSenderId: '8731740027',
    projectId: 'basededatos-c4252',
    storageBucket: 'basededatos-c4252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQMB0l60C_AW2JtPK1wLRdMGROY_wwm7o',
    appId: '1:8731740027:ios:dbc3ce79136542cf2e9fde',
    messagingSenderId: '8731740027',
    projectId: 'basededatos-c4252',
    storageBucket: 'basededatos-c4252.firebasestorage.app',
    iosBundleId: 'com.adanjacob.appflutter6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQMB0l60C_AW2JtPK1wLRdMGROY_wwm7o',
    appId: '1:8731740027:ios:dbc3ce79136542cf2e9fde',
    messagingSenderId: '8731740027',
    projectId: 'basededatos-c4252',
    storageBucket: 'basededatos-c4252.firebasestorage.app',
    iosBundleId: 'com.adanjacob.appflutter6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw-0IWqhiN-qf3u1ZlRk-ypwjhwIpzbAY',
    appId: '1:8731740027:web:4615c6a7b7d234082e9fde',
    messagingSenderId: '8731740027',
    projectId: 'basededatos-c4252',
    authDomain: 'basededatos-c4252.firebaseapp.com',
    storageBucket: 'basededatos-c4252.firebasestorage.app',
    measurementId: 'G-E2VC1XE319',
  );
}
